va_macro_dlkm
lzo-rle
wcd_core_dlkm
lzo_compress
q6_notifier_dlkm
platform_dlkm
lzo_decompress
bt_fm_slim
q6_dlkm
camera
wcd938x_slave_dlkm
aw882xx_k419
wcd937x_slave_dlkm
swr_dlkm
mbhc_dlkm
pinctrl_lpi_dlkm
swr_ctrl_dlkm
lzo
stub_dlkm
apr_dlkm
wsa881x_analog_dlkm
wcd937x_dlkm
rdbg
aw882xx_acf
q6_pdr_dlkm
adsp_loader_dlkm
zram
snd_event_dlkm
wcd938x_dlkm
native_dlkm
bolero_cdc_dlkm
wcd9xxx_dlkm
tx_macro_dlkm
rx_macro_dlkm
btpower
machine_dlkm
wlan
rmnet_core
rmnet_ctl
rmnet_offload
rmnet_shs
utags
mmi_relay
mmi_info
mmi_annotate
sensors_class
exfat
qpnp_adaptive_charge
rbs_fod_mmi
aw862x
wl2868c
cci_intf
sensors_class
mmi_relay
touchscreen_mmi
goodix_brl_mmi
nfc_i2c
sx937x_sar
mmi_sys_temp
mm8013c_fg_mmi
tcpc_class
tcpc_rt1711h
adapter_class
rt_pd_manager
sgm4154x_charger
bq2589x_charger
mmi_charger
mmi_discrete_charger_class
mmi_discrete_charger
mmi_discrete_turbo_charger
wl2864c
bq25980_mmi_iio
leds_aw2033
cps4019_wls_charger

